#!/bin/bash

IMAGETAG=1.4.1

# Print the usage message
function printHelp() {
  echo "Usage: "
  echo "  fabric-client <command>"
  echo "    <command> - one of 'start', 'stop', 'restart' or 'clear'"
  echo "      - 'start' - start the node with docker-compose up"
  echo "      - 'stop' - stop the node with docker-compose down"
  echo "      - 'restart' - restart the node"
  echo "      - 'clear' - clear the node's resource"
}

if [ "$1" == "start" ]; then ## Start
  docker-compose -f docker-compose-peer.yaml start
elif [ "$1" == "stop" ]; then ## Stop 
  docker-compose -f docker-compose-peer.yaml stop
elif [ "$1" == "restart" ]; then ## Restart
  docker-compose -f docker-compose-peer.yaml restart
elif [ "$1" == "up" ]; then
  docker-compose -f docker-compose-peer.yaml up -d
elif [ "$1" == "down" ]; then
  docker-compose -f docker-compose-peer.yaml down
elif [ "$1" == "clear" ]; then ## Clear
  docker rm $(docker ps -aq) -f
  docker volume prune
elif [ "$1" == "logs" ]; then ## log
  docker logs -f peer0.org2.csxoa.cn
else
  printHelp
  exit 1
fi
